"""Add sustainability models

Revision ID: 10294c569830
Revises: aafed7f763e8
Create Date: 2026-05-17 12:56:32.510062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10294c569830'
down_revision: Union[str, Sequence[str], None] = 'aafed7f763e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esg_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_goals_id'), 'esg_goals', ['id'], unique=False)
    op.create_index(op.f('ix_esg_goals_organization_id'), 'esg_goals', ['organization_id'], unique=False)
    op.create_table('sustainability_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('co2_saved_kg', sa.Float(), nullable=True),
    sa.Column('waste_diverted_kg', sa.Float(), nullable=True),
    sa.Column('water_saved_liters', sa.Float(), nullable=True),
    sa.Column('energy_saved_kwh', sa.Float(), nullable=True),
    sa.Column('plastic_kg', sa.Float(), nullable=True),
    sa.Column('paper_kg', sa.Float(), nullable=True),
    sa.Column('metal_kg', sa.Float(), nullable=True),
    sa.Column('organic_kg', sa.Float(), nullable=True),
    sa.Column('other_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sust_metrics_org_date', 'sustainability_metrics', ['organization_id', 'date'], unique=False)
    op.create_index(op.f('ix_sustainability_metrics_date'), 'sustainability_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_sustainability_metrics_id'), 'sustainability_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_sustainability_metrics_organization_id'), 'sustainability_metrics', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sustainability_metrics_organization_id'), table_name='sustainability_metrics')
    op.drop_index(op.f('ix_sustainability_metrics_id'), table_name='sustainability_metrics')
    op.drop_index(op.f('ix_sustainability_metrics_date'), table_name='sustainability_metrics')
    op.drop_index('ix_sust_metrics_org_date', table_name='sustainability_metrics')
    op.drop_table('sustainability_metrics')
    op.drop_index(op.f('ix_esg_goals_organization_id'), table_name='esg_goals')
    op.drop_index(op.f('ix_esg_goals_id'), table_name='esg_goals')
    op.drop_table('esg_goals')
    # ### end Alembic commands ###
