"""Add analytics_events, daily_metrics, sustainability_metrics and indexes

Revision ID: 22225f99d1fc
Revises: e77a05f895e8
Create Date: 2026-05-17 12:12:18.840675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22225f99d1fc'
down_revision: Union[str, Sequence[str], None] = 'e77a05f895e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_metrics', sa.Column('total_waste_kg', sa.Float(), nullable=True))
    op.add_column('daily_metrics', sa.Column('total_co2_saved_kg', sa.Float(), nullable=True))
    op.add_column('daily_metrics', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_metrics', 'updated_at')
    op.drop_column('daily_metrics', 'total_co2_saved_kg')
    op.drop_column('daily_metrics', 'total_waste_kg')
    # ### end Alembic commands ###
