"""add_pickup_module_tables

Revision ID: 2280c99d3606
Revises: ca962dca7c4e
Create Date: 2026-02-22 17:48:42.551650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2280c99d3606'
down_revision: Union[str, Sequence[str], None] = 'ca962dca7c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('waste_type', sa.Enum('GENERAL', 'RECYCLABLE', 'HAZARDOUS', 'ORGANIC', 'ELECTRONIC', name='wastetype'), nullable=False),
    sa.Column('waste_weight', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='pickupstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('waste_weight >= 0', name='check_waste_weight_non_negative'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickups_id'), 'pickups', ['id'], unique=False)
    op.create_index(op.f('ix_pickups_organization_id'), 'pickups', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pickups_scheduled_at'), 'pickups', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_pickups_status'), 'pickups', ['status'], unique=False)
    op.create_table('pickup_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'ACCEPTED', 'REJECTED', 'COMPLETED', name='assignmentstatus'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pickup_id', 'status', name='uq_active_assignment_per_pickup')
    )
    op.create_index(op.f('ix_pickup_assignments_driver_id'), 'pickup_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_pickup_assignments_id'), 'pickup_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_pickup_assignments_pickup_id'), 'pickup_assignments', ['pickup_id'], unique=False)
    op.create_table('pickup_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(length=1000), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', name='mediatype'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_media_id'), 'pickup_media', ['id'], unique=False)
    op.create_index(op.f('ix_pickup_media_pickup_id'), 'pickup_media', ['pickup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pickup_media_pickup_id'), table_name='pickup_media')
    op.drop_index(op.f('ix_pickup_media_id'), table_name='pickup_media')
    op.drop_table('pickup_media')
    op.drop_index(op.f('ix_pickup_assignments_pickup_id'), table_name='pickup_assignments')
    op.drop_index(op.f('ix_pickup_assignments_id'), table_name='pickup_assignments')
    op.drop_index(op.f('ix_pickup_assignments_driver_id'), table_name='pickup_assignments')
    op.drop_table('pickup_assignments')
    op.drop_index(op.f('ix_pickups_status'), table_name='pickups')
    op.drop_index(op.f('ix_pickups_scheduled_at'), table_name='pickups')
    op.drop_index(op.f('ix_pickups_organization_id'), table_name='pickups')
    op.drop_index(op.f('ix_pickups_id'), table_name='pickups')
    op.drop_table('pickups')
    # ### end Alembic commands ###
