"""add admin indexes

Revision ID: 315544159349
Revises: 624280acbeef
Create Date: 2026-05-18 17:27:57.252754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '315544159349'
down_revision: Union[str, Sequence[str], None] = '624280acbeef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ARRIVED', 'COMPLETED', 'SKIPPED', name='tripstopstatus', native_enum=False), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('completion_time', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_stops_status'), 'trip_stops', ['status'], unique=False)
    op.create_index(op.f('ix_trip_stops_trip_id'), 'trip_stops', ['trip_id'], unique=False)
    op.alter_column('incidents', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('incidents', 'severity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentseverity', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.alter_column('incidents', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='incidentstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::character varying"))
    op.alter_column('incidents', 'resolution_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('incidents', 'reported_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('incidents', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('incidents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_incidents_driver_id'), 'incidents', ['driver_id'], unique=False)
    op.create_index(op.f('ix_incidents_organization_id'), 'incidents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_trip_id'), 'incidents', ['trip_id'], unique=False)
    op.create_index(op.f('ix_incidents_vehicle_id'), 'incidents', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'incidents', 'users', ['reported_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'incidents', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'incidents', 'trips', ['trip_id'], ['id'], ondelete='SET NULL')
    op.alter_column('optimized_routes', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('optimized_routes', 'total_distance_km',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('optimized_routes', 'estimated_duration_min',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('optimized_routes', 'optimized_polyline',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_optimized_routes_id'), 'optimized_routes', ['id'], unique=False)
    op.drop_constraint(op.f('optimized_routes_organization_id_fkey'), 'optimized_routes', type_='foreignkey')
    op.drop_constraint(op.f('optimized_routes_vehicle_id_fkey'), 'optimized_routes', type_='foreignkey')
    op.drop_constraint(op.f('optimized_routes_driver_id_fkey'), 'optimized_routes', type_='foreignkey')
    op.create_foreign_key(None, 'optimized_routes', 'users', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'optimized_routes', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'optimized_routes', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.alter_column('route_waypoints', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_route_waypoints_id'), 'route_waypoints', ['id'], unique=False)
    op.drop_constraint(op.f('route_waypoints_optimized_route_id_fkey'), 'route_waypoints', type_='foreignkey')
    op.create_foreign_key(None, 'route_waypoints', 'optimized_routes', ['optimized_route_id'], ['id'])
    op.add_column('trips', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('trips', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'EN_ROUTE', 'ACTIVE_LOADING', 'PAUSED', 'COMPLETED', 'CANCELLED', name='tripstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_organization_id'), 'trips', ['organization_id'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_user_roles_org_id'), 'user_roles', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_driver_id'), 'vehicle_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_vehicle_id'), 'vehicle_assignments', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_maintenance_vehicle_id'), 'vehicle_maintenance', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_telemetry_organization_id'), 'vehicle_telemetry', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vehicle_telemetry_timestamp'), 'vehicle_telemetry', ['timestamp'], unique=False)
    op.create_index(op.f('ix_vehicle_telemetry_vehicle_id'), 'vehicle_telemetry', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicles_organization_id'), 'vehicles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_organization_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicle_telemetry_vehicle_id'), table_name='vehicle_telemetry')
    op.drop_index(op.f('ix_vehicle_telemetry_timestamp'), table_name='vehicle_telemetry')
    op.drop_index(op.f('ix_vehicle_telemetry_organization_id'), table_name='vehicle_telemetry')
    op.drop_index(op.f('ix_vehicle_maintenance_vehicle_id'), table_name='vehicle_maintenance')
    op.drop_index(op.f('ix_vehicle_assignments_vehicle_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_driver_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_org_id'), table_name='user_roles')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_organization_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.alter_column('trips', 'status',
               existing_type=sa.Enum('PENDING', 'EN_ROUTE', 'ACTIVE_LOADING', 'PAUSED', 'COMPLETED', 'CANCELLED', name='tripstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_column('trips', 'end_time')
    op.drop_column('trips', 'start_time')
    op.drop_constraint(None, 'route_waypoints', type_='foreignkey')
    op.create_foreign_key(op.f('route_waypoints_optimized_route_id_fkey'), 'route_waypoints', 'optimized_routes', ['optimized_route_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_route_waypoints_id'), table_name='route_waypoints')
    op.alter_column('route_waypoints', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'optimized_routes', type_='foreignkey')
    op.drop_constraint(None, 'optimized_routes', type_='foreignkey')
    op.drop_constraint(None, 'optimized_routes', type_='foreignkey')
    op.create_foreign_key(op.f('optimized_routes_driver_id_fkey'), 'optimized_routes', 'users', ['driver_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('optimized_routes_vehicle_id_fkey'), 'optimized_routes', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('optimized_routes_organization_id_fkey'), 'optimized_routes', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_optimized_routes_id'), table_name='optimized_routes')
    op.alter_column('optimized_routes', 'optimized_polyline',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('optimized_routes', 'estimated_duration_min',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('optimized_routes', 'total_distance_km',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('optimized_routes', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_index(op.f('ix_incidents_vehicle_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_trip_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_organization_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_driver_id'), table_name='incidents')
    op.alter_column('incidents', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('incidents', 'resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('incidents', 'reported_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('incidents', 'resolution_notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('incidents', 'status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='incidentstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::character varying"))
    op.alter_column('incidents', 'severity',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentseverity', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.alter_column('incidents', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_trip_stops_trip_id'), table_name='trip_stops')
    op.drop_index(op.f('ix_trip_stops_status'), table_name='trip_stops')
    op.drop_table('trip_stops')
    # ### end Alembic commands ###
