"""add_pickup_priority

Revision ID: 3165d01729cd
Revises: ebe0fee28a8c
Create Date: 2026-05-17 02:55:32.806272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3165d01729cd'
down_revision: Union[str, Sequence[str], None] = 'ebe0fee28a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pickup_priority = sa.Enum('HIGH', 'NORMAL', 'LOW', name='pickuppriority')
    pickup_priority.create(op.get_bind(), checkfirst=True)
    
    op.add_column('pickups', sa.Column('priority', pickup_priority, nullable=False, server_default='NORMAL'))
    op.create_index(op.f('ix_pickups_priority'), 'pickups', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pickups_priority'), table_name='pickups')
    op.drop_column('pickups', 'priority')
    
    pickup_priority = sa.Enum('HIGH', 'NORMAL', 'LOW', name='pickuppriority')
    pickup_priority.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
