"""add eco goals table

Revision ID: 33a354a2f9cc
Revises: f92983bcbbb7
Create Date: 2026-05-18 11:57:08.215738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a354a2f9cc'
down_revision: Union[str, Sequence[str], None] = 'f92983bcbbb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eco_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('metric_type', sa.Enum('CO2_SAVED', 'WASTE_DIVERTED', 'CLEAN_ENERGY', 'ACTIVE_VEHICLES', name='metrictype', native_enum=False, length=50), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eco_goals_id'), 'eco_goals', ['id'], unique=False)
    op.create_index(op.f('ix_eco_goals_organization_id'), 'eco_goals', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eco_goals_organization_id'), table_name='eco_goals')
    op.drop_index(op.f('ix_eco_goals_id'), table_name='eco_goals')
    op.drop_table('eco_goals')
    # ### end Alembic commands ###
