"""add pickup exceptions table

Revision ID: 345d9d676af2
Revises: f1f132b84b56
Create Date: 2026-05-16 22:34:06.650393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345d9d676af2'
down_revision: Union[str, Sequence[str], None] = 'f1f132b84b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickup_exceptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pickup_id', sa.Integer(), nullable=False),
        sa.Column('exception_type', sa.Enum('GATE_LOCKED', 'CUSTOMER_NOT_PRESENT', 'HAZARDOUS_MATERIAL', 'VOLUME_EXCEEDED', 'ACCESS_DENIED', 'VEHICLE_ISSUE', 'OTHER', name='exceptiontype'), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('reported_by_id', sa.Integer(), nullable=True),
        sa.Column('resolved', sa.Boolean(), nullable=False),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.Column('resolved_by_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['pickup_id'], ['pickups.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pickup_exceptions_pickup_id', 'pickup_exceptions', ['pickup_id'], unique=False)
    op.create_index('ix_pickup_exceptions_resolved', 'pickup_exceptions', ['resolved'], unique=False)
    op.create_index('ix_pickup_exceptions_type', 'pickup_exceptions', ['exception_type'], unique=False)
    op.create_index(op.f('ix_pickup_exceptions_id'), 'pickup_exceptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pickup_exceptions_id'), table_name='pickup_exceptions')
    op.drop_index('ix_pickup_exceptions_type', table_name='pickup_exceptions')
    op.drop_index('ix_pickup_exceptions_resolved', table_name='pickup_exceptions')
    op.drop_index('ix_pickup_exceptions_pickup_id', table_name='pickup_exceptions')
    op.drop_table('pickup_exceptions')
    sa.Enum(name='exceptiontype').drop(op.get_bind())
    # ### end Alembic commands ###
