"""create_pickup_activities_table

Revision ID: 4505b5f1ffd0
Revises: 345d9d676af2
Create Date: 2026-05-17 01:30:10.374418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4505b5f1ffd0'
down_revision: Union[str, Sequence[str], None] = '345d9d676af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickup_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.Enum('CREATED', 'STATUS_UPDATED', 'ASSIGNED', 'UNASSIGNED', 'RESCHEDULED', 'EXCEPTION_REPORTED', 'EXCEPTION_RESOLVED', 'MANUAL_NOTE', name='activitytype'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_activities_id'), 'pickup_activities', ['id'], unique=False)
    op.create_index(op.f('ix_pickup_activities_pickup_id'), 'pickup_activities', ['pickup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pickup_activities_pickup_id'), table_name='pickup_activities')
    op.drop_index(op.f('ix_pickup_activities_id'), table_name='pickup_activities')
    op.drop_table('pickup_activities')
    # ### end Alembic commands ###
