"""enterprise_rbac_safety_and_audit_logs

Revision ID: 4d784f71d074
Revises: 61472c1b89ea
Create Date: 2026-02-23 17:38:05.096079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d784f71d074'
down_revision: Union[str, Sequence[str], None] = '61472c1b89ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add columns as nullable first or with default
    op.add_column('audit_logs', sa.Column('entity_type', sa.String(length=50), nullable=False, server_default='role'))
    op.add_column('audit_logs', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('old_value', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('new_value', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('changed_by', sa.Integer(), nullable=True))

    # 2. Backfill existing data
    op.execute('UPDATE audit_logs SET changed_by = user_id WHERE changed_by IS NULL')
    op.execute('UPDATE audit_logs SET entity_id = 0 WHERE entity_id IS NULL')

    # 3. Alter columns to NOT NULL
    op.alter_column('audit_logs', 'entity_id', existing_type=sa.Integer(), nullable=False)
    op.alter_column('audit_logs', 'changed_by', existing_type=sa.Integer(), nullable=False)

    # 4. Handle foreign keys and removals
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['changed_by'], ['id'])
    op.drop_column('audit_logs', 'meta')
    op.drop_column('audit_logs', 'user_id')
    
    # role
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_active')
    op.add_column('audit_logs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('meta', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_column('audit_logs', 'changed_by')
    op.drop_column('audit_logs', 'new_value')
    op.drop_column('audit_logs', 'old_value')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    # ### end Alembic commands ###
