"""update organization model

Revision ID: 60c26fdc1532
Revises: 54e8565a5072
Create Date: 2026-02-18 15:38:38.321217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c26fdc1532'
down_revision: Union[str, Sequence[str], None] = '54e8565a5072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create columns as nullable first
    op.add_column('organization_categories', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('organizations', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('pincode', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('organizations', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('organizations', sa.Column('contact_number', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('is_active', sa.Boolean(), nullable=True))

    # --- Data Migration Start ---
    # 2. Insert a default category if none exists
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    # Check if any category exists
    default_category_id = session.execute(
        sa.text("SELECT id FROM organization_categories LIMIT 1")
    ).scalar()

    if not default_category_id:
        # Create a default category
        session.execute(
            sa.text("INSERT INTO organization_categories (name, description, is_active, created_at, updated_at) VALUES (:name, :desc, :active, NOW(), NOW())"),
            {"name": "Default", "desc": "Default Category", "active": True}
        )
        default_category_id = session.execute(
            sa.text("SELECT id FROM organization_categories WHERE name = 'Default'")
        ).scalar()
    
    # 3. Update existing organizations to use this category_id
    if default_category_id:
        session.execute(
            sa.text("UPDATE organizations SET category_id = :cat_id WHERE category_id IS NULL"),
            {"cat_id": default_category_id}
        )
    
    session.commit()
    # --- Data Migration End ---

    # 4. Now enforce non-nullable constraint
    op.alter_column('organizations', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('organizations', 'is_active')
    op.drop_column('organizations', 'status')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'contact_number')
    op.drop_column('organizations', 'longitude')
    op.drop_column('organizations', 'latitude')
    op.drop_column('organizations', 'pincode')
    op.drop_column('organizations', 'state')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'address')
    op.drop_column('organization_categories', 'is_active')
    # ### end Alembic commands ###
