"""add_is_system_role_and_rbac_manage

Revision ID: 8279a5a0fb15
Revises: 5c0478182f92
Create Date: 2026-02-23 13:42:50.914759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_is_system_role_and_rbac_manage

Revision ID: 8279a5a0fb15
Revises: 5c0478182f92
Create Date: 2026-02-23 13:42:50.914759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8279a5a0fb15'
down_revision: Union[str, Sequence[str], None] = '5c0478182f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_system_role', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # Set existing core roles to system roles
    op.execute("UPDATE roles SET is_system_role = true WHERE name IN ('ADMIN', 'ORGANIZATION', 'DRIVER', 'CUSTOMER');")

    # Seed the rbac.manage permission
    op.execute(
        "INSERT INTO permissions (code, description, created_at, updated_at) "
        "VALUES ('rbac.manage', 'Allows full dynamic management of Roles and Permissions', NOW(), NOW()) "
        "ON CONFLICT (code) DO NOTHING;"
    )

    # Attach rbac.manage to ADMIN
    op.execute(
        "INSERT INTO role_permissions (role_id, permission_id, created_at, updated_at) "
        "SELECT r.id, p.id, NOW(), NOW() "
        "FROM roles r, permissions p "
        "WHERE r.name = 'ADMIN' AND p.code = 'rbac.manage' "
        "ON CONFLICT DO NOTHING;"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Remove rbac.manage permission link
    op.execute(
        "DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code = 'rbac.manage');"
    )
    
    # Remove the permission
    op.execute("DELETE FROM permissions WHERE code = 'rbac.manage';")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_system_role')
    # ### end Alembic commands ###
