"""add_analytics_composite_indexes

Revision ID: 8dc27a258d85
Revises: d978e56b660b
Create Date: 2026-05-12 11:26:14.977171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc27a258d85'
down_revision: Union[str, Sequence[str], None] = 'd978e56b660b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_analytics_events_org_created', 'analytics_events', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_analytics_events_type_created', 'analytics_events', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_daily_metrics_org_date', 'daily_metrics', ['organization_id', 'date'], unique=False)
    op.create_index('ix_pickups_org_created', 'pickups', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_pickups_org_status', 'pickups', ['organization_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pickups_org_status', table_name='pickups')
    op.drop_index('ix_pickups_org_created', table_name='pickups')
    op.drop_index('ix_daily_metrics_org_date', table_name='daily_metrics')
    op.drop_index('ix_analytics_events_type_created', table_name='analytics_events')
    op.drop_index('ix_analytics_events_org_created', table_name='analytics_events')
    # ### end Alembic commands ###
