"""create_analytics_metrics_tables

Revision ID: a0a6e8529400
Revises: 80436eafae31
Create Date: 2026-05-09 22:03:27.190552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a6e8529400'
down_revision: Union[str, Sequence[str], None] = '80436eafae31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('LOGIN', 'LOGOUT', 'PICKUP_CREATED', 'PICKUP_COMPLETED', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'SUB_UPGRADED', 'SUB_CANCELLED', 'SECURITY_ALERT', name='eventtype'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_id'), 'analytics_events', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_events_organization_id'), 'analytics_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_pickups', sa.Integer(), nullable=True),
    sa.Column('completed_pickups', sa.Integer(), nullable=True),
    sa.Column('pending_pickups', sa.Integer(), nullable=True),
    sa.Column('cancelled_pickups', sa.Integer(), nullable=True),
    sa.Column('active_drivers', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_metrics_date'), 'daily_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_daily_metrics_id'), 'daily_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_daily_metrics_organization_id'), 'daily_metrics', ['organization_id'], unique=False)
    op.create_table('driver_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed_pickups', sa.Integer(), nullable=True),
    sa.Column('total_weight_handled', sa.Float(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_metrics_date'), 'driver_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_driver_metrics_driver_id'), 'driver_metrics', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_metrics_id'), 'driver_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_driver_metrics_organization_id'), 'driver_metrics', ['organization_id'], unique=False)
    op.create_table('pickup_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('waste_type', sa.String(length=50), nullable=False),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('pickup_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_metrics_date'), 'pickup_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_pickup_metrics_id'), 'pickup_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_pickup_metrics_organization_id'), 'pickup_metrics', ['organization_id'], unique=False)
    op.create_table('revenue_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('successful_payments', sa.Integer(), nullable=True),
    sa.Column('failed_payments', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_metrics_date'), 'revenue_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_revenue_metrics_id'), 'revenue_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_revenue_metrics_organization_id'), 'revenue_metrics', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenue_metrics_organization_id'), table_name='revenue_metrics')
    op.drop_index(op.f('ix_revenue_metrics_id'), table_name='revenue_metrics')
    op.drop_index(op.f('ix_revenue_metrics_date'), table_name='revenue_metrics')
    op.drop_table('revenue_metrics')
    op.drop_index(op.f('ix_pickup_metrics_organization_id'), table_name='pickup_metrics')
    op.drop_index(op.f('ix_pickup_metrics_id'), table_name='pickup_metrics')
    op.drop_index(op.f('ix_pickup_metrics_date'), table_name='pickup_metrics')
    op.drop_table('pickup_metrics')
    op.drop_index(op.f('ix_driver_metrics_organization_id'), table_name='driver_metrics')
    op.drop_index(op.f('ix_driver_metrics_id'), table_name='driver_metrics')
    op.drop_index(op.f('ix_driver_metrics_driver_id'), table_name='driver_metrics')
    op.drop_index(op.f('ix_driver_metrics_date'), table_name='driver_metrics')
    op.drop_table('driver_metrics')
    op.drop_index(op.f('ix_daily_metrics_organization_id'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_id'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_date'), table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_organization_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
