"""add accepted info to invitation

Revision ID: a884310f0762
Revises: 63bae8ae914e
Create Date: 2026-05-18 13:09:28.554951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a884310f0762'
down_revision: Union[str, Sequence[str], None] = '63bae8ae914e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('accepted_at', sa.DateTime(), nullable=True))
    op.add_column('invitations', sa.Column('accepted_by_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invitations_accepted_by_user_id'), 'invitations', ['accepted_by_user_id'], unique=False)
    op.create_foreign_key(None, 'invitations', 'users', ['accepted_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_index(op.f('ix_invitations_accepted_by_user_id'), table_name='invitations')
    op.drop_column('invitations', 'accepted_by_user_id')
    op.drop_column('invitations', 'accepted_at')
    # ### end Alembic commands ###
