"""enterprise_payment_hardening

Revision ID: ad2534d761f9
Revises: 96969f74f9c4
Create Date: 2026-02-24 15:53:29.493457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""enterprise_payment_hardening

Revision ID: ad2534d761f9
Revises: 96969f74f9c4
Create Date: 2026-02-24 15:53:29.493457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad2534d761f9'
down_revision: Union[str, Sequence[str], None] = '96969f74f9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use autocommit block for ALTER TYPE to avoid transaction lock
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE subscriptionstatus ADD VALUE IF NOT EXISTS 'GRACE'")
        op.execute("ALTER TYPE paymentstatus ADD VALUE IF NOT EXISTS 'DISPUTED'")
        
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('gateway_signature', sa.String(length=255), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_id'), 'payment_events', ['id'], unique=False)
    op.create_index(op.f('ix_payment_events_payment_id'), 'payment_events', ['payment_id'], unique=False)
    op.add_column('invoices', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.create_index('ix_one_success_payment', 'payments', ['invoice_id'], unique=True, postgresql_where=sa.text("status = 'SUCCESS'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_one_success_payment', table_name='payments', postgresql_where=sa.text("status = 'SUCCESS'"))
    op.drop_column('invoices', 'final_amount')
    op.drop_column('invoices', 'tax_amount')
    op.drop_column('invoices', 'discount_amount')
    op.drop_index(op.f('ix_payment_events_payment_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_id'), table_name='payment_events')
    op.drop_table('payment_events')
    # ### end Alembic commands ###
