"""add organization_members

Revision ID: d8e3ea99e480
Revises: ad2534d761f9
Create Date: 2026-02-26 23:53:42.512902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e3ea99e480'
down_revision: Union[str, Sequence[str], None] = 'ad2534d761f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'SUSPENDED', 'REMOVED', name='membershipstatus'), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_member')
    )
    op.create_index(op.f('ix_organization_members_id'), 'organization_members', ['id'], unique=False)
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # --- INJECT RBAC PERMISSIONS SEED ---
    # Define the new membership permissions
    permissions = [
        {'code': 'membership.view', 'description': 'View organization members'},
        {'code': 'membership.create', 'description': 'Invite/Add organization members'},
        {'code': 'membership.update', 'description': 'Update member roles and statuses'},
        {'code': 'membership.delete', 'description': 'Remove organization members'},
    ]

    # Insert permissions
    for p in permissions:
        op.execute(f"""
            INSERT INTO permissions (code, description, created_at, updated_at) 
            VALUES ('{p['code']}', '{p['description']}', NOW(), NOW()) 
            ON CONFLICT (code) DO NOTHING;
        """)

    # Assign all 4 permissions to ADMIN and ORGANIZATION roles
    op.execute("""
        INSERT INTO role_permissions (role_id, permission_id, created_at, updated_at)
        SELECT r.id, p.id, NOW(), NOW()
        FROM roles r
        CROSS JOIN permissions p
        WHERE r.name IN ('ADMIN', 'ORGANIZATION')
          AND p.code IN ('membership.view', 'membership.create', 'membership.update', 'membership.delete')
        ON CONFLICT ON CONSTRAINT uq_role_permission DO NOTHING;
    """)
    # --- END INJECT RBAC PERMISSIONS SEED ---


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_id'), table_name='organization_members')
    op.drop_table('organization_members')
    
    # Drop the enum
    op.execute("DROP TYPE membershipstatus")
    # ### end Alembic commands ###

    # --- REMOVE RBAC PERMISSIONS SEED ---
    op.execute("""
        DELETE FROM role_permissions 
        WHERE permission_id IN (
            SELECT id FROM permissions WHERE code IN ('membership.view', 'membership.create', 'membership.update', 'membership.delete')
        );
    """)
    op.execute("""
        DELETE FROM permissions 
        WHERE code IN ('membership.view', 'membership.create', 'membership.update', 'membership.delete');
    """)
    # --- END REMOVE RBAC PERMISSIONS SEED ---
