"""add_recurring_pickups_table

Revision ID: e77a05f895e8
Revises: 3165d01729cd
Create Date: 2026-05-17 03:16:06.073235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77a05f895e8'
down_revision: Union[str, Sequence[str], None] = '3165d01729cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_pickups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('waste_type', sa.String(), nullable=False),
    sa.Column('waste_weight', sa.Float(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='recurringfrequency'), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_pickups_id'), 'recurring_pickups', ['id'], unique=False)
    op.create_index(op.f('ix_recurring_pickups_is_active'), 'recurring_pickups', ['is_active'], unique=False)
    op.create_index(op.f('ix_recurring_pickups_next_run_at'), 'recurring_pickups', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_recurring_pickups_organization_id'), 'recurring_pickups', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_pickups_organization_id'), table_name='recurring_pickups')
    op.drop_index(op.f('ix_recurring_pickups_next_run_at'), table_name='recurring_pickups')
    op.drop_index(op.f('ix_recurring_pickups_is_active'), table_name='recurring_pickups')
    op.drop_index(op.f('ix_recurring_pickups_id'), table_name='recurring_pickups')
    op.drop_table('recurring_pickups')
    # ### end Alembic commands ###
