"""add_materialized_metrics_tables

Revision ID: f1f132b84b56
Revises: 8dc27a258d85
Create Date: 2026-05-12 11:28:25.228119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f132b84b56'
down_revision: Union[str, Sequence[str], None] = '8dc27a258d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hourly_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('total_pickups', sa.Integer(), nullable=True),
    sa.Column('completed_pickups', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hourly_metrics_id'), 'hourly_metrics', ['id'], unique=False)
    op.create_index('ix_hourly_metrics_org_ts', 'hourly_metrics', ['organization_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_hourly_metrics_organization_id'), 'hourly_metrics', ['organization_id'], unique=False)
    op.create_index(op.f('ix_hourly_metrics_timestamp'), 'hourly_metrics', ['timestamp'], unique=False)
    op.create_table('monthly_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_pickups', sa.Integer(), nullable=True),
    sa.Column('completed_pickups', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_metrics_id'), 'monthly_metrics', ['id'], unique=False)
    op.create_index('ix_monthly_metrics_org_year_month', 'monthly_metrics', ['organization_id', 'year', 'month'], unique=False)
    op.create_index(op.f('ix_monthly_metrics_organization_id'), 'monthly_metrics', ['organization_id'], unique=False)
    op.create_table('weekly_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('total_pickups', sa.Integer(), nullable=True),
    sa.Column('completed_pickups', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_metrics_id'), 'weekly_metrics', ['id'], unique=False)
    op.create_index('ix_weekly_metrics_org_year_week', 'weekly_metrics', ['organization_id', 'year', 'week_number'], unique=False)
    op.create_index(op.f('ix_weekly_metrics_organization_id'), 'weekly_metrics', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_metrics_organization_id'), table_name='weekly_metrics')
    op.drop_index('ix_weekly_metrics_org_year_week', table_name='weekly_metrics')
    op.drop_index(op.f('ix_weekly_metrics_id'), table_name='weekly_metrics')
    op.drop_table('weekly_metrics')
    op.drop_index(op.f('ix_monthly_metrics_organization_id'), table_name='monthly_metrics')
    op.drop_index('ix_monthly_metrics_org_year_month', table_name='monthly_metrics')
    op.drop_index(op.f('ix_monthly_metrics_id'), table_name='monthly_metrics')
    op.drop_table('monthly_metrics')
    op.drop_index(op.f('ix_hourly_metrics_timestamp'), table_name='hourly_metrics')
    op.drop_index(op.f('ix_hourly_metrics_organization_id'), table_name='hourly_metrics')
    op.drop_index('ix_hourly_metrics_org_ts', table_name='hourly_metrics')
    op.drop_index(op.f('ix_hourly_metrics_id'), table_name='hourly_metrics')
    op.drop_table('hourly_metrics')
    # ### end Alembic commands ###
