"""Add driver operations, maintenance and incident models

Revision ID: f92983bcbbb7
Revises: f6b81932e8d1
Create Date: 2026-05-18 00:45:22.207655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92983bcbbb7'
down_revision: Union[str, Sequence[str], None] = 'f6b81932e8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='documentverificationstatus', native_enum=False), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_documents_driver_id'), 'driver_documents', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_documents_organization_id'), 'driver_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_driver_documents_verification_status'), 'driver_documents', ['verification_status'], unique=False)
    op.create_table('driver_shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('clock_in_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clock_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='shiftstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_shifts_driver_id'), 'driver_shifts', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_shifts_organization_id'), 'driver_shifts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_driver_shifts_status'), 'driver_shifts', ['status'], unique=False)
    op.create_table('vehicle_maintenance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='maintenancestatus', native_enum=False), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_maintenance_organization_id'), 'vehicle_maintenance', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vehicle_maintenance_status'), 'vehicle_maintenance', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_maintenance_vehicle_id'), 'vehicle_maintenance', ['vehicle_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentseverity', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='incidentstatus', native_enum=False), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('reported_by', sa.Integer(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_driver_id'), 'incidents', ['driver_id'], unique=False)
    op.create_index(op.f('ix_incidents_organization_id'), 'incidents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_trip_id'), 'incidents', ['trip_id'], unique=False)
    op.create_index(op.f('ix_incidents_vehicle_id'), 'incidents', ['vehicle_id'], unique=False)
    op.drop_constraint(op.f('optimized_routes_vehicle_id_fkey'), 'optimized_routes', type_='foreignkey')
    op.create_foreign_key(None, 'optimized_routes', 'vehicles', ['vehicle_id'], ['id'])
    op.alter_column('trip_stops', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'ARRIVED', 'COMPLETED', 'SKIPPED', name='tripstopstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'EN_ROUTE', 'ACTIVE_LOADING', 'COMPLETED', name='tripstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('vehicles', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'DELETED', name='vehiclestatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'INACTIVE'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'DELETED', name='vehiclestatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'INACTIVE'::character varying"))
    op.alter_column('trips', 'status',
               existing_type=sa.Enum('PENDING', 'EN_ROUTE', 'ACTIVE_LOADING', 'COMPLETED', name='tripstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('trip_stops', 'status',
               existing_type=sa.Enum('PENDING', 'ARRIVED', 'COMPLETED', 'SKIPPED', name='tripstopstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'optimized_routes', type_='foreignkey')
    op.create_foreign_key(op.f('optimized_routes_vehicle_id_fkey'), 'optimized_routes', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_incidents_vehicle_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_trip_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_organization_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_driver_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_vehicle_maintenance_vehicle_id'), table_name='vehicle_maintenance')
    op.drop_index(op.f('ix_vehicle_maintenance_status'), table_name='vehicle_maintenance')
    op.drop_index(op.f('ix_vehicle_maintenance_organization_id'), table_name='vehicle_maintenance')
    op.drop_table('vehicle_maintenance')
    op.drop_index(op.f('ix_driver_shifts_status'), table_name='driver_shifts')
    op.drop_index(op.f('ix_driver_shifts_organization_id'), table_name='driver_shifts')
    op.drop_index(op.f('ix_driver_shifts_driver_id'), table_name='driver_shifts')
    op.drop_table('driver_shifts')
    op.drop_index(op.f('ix_driver_documents_verification_status'), table_name='driver_documents')
    op.drop_index(op.f('ix_driver_documents_organization_id'), table_name='driver_documents')
    op.drop_index(op.f('ix_driver_documents_driver_id'), table_name='driver_documents')
    op.drop_table('driver_documents')
    # ### end Alembic commands ###
